Add the setting page in the dev branch.
algosup/2023-2024-project-5-flutter-team-3 pull request #21
Opened 2024-06-06 08:34 UTC by LucasAub

Add the settings page on the dev branch to have the latest version of the application on this branch.

2024-06-06 08:39 UTC, MaximeAlgosup commented on adopte_a_candidate/lib/pages/log_in.dart
We should not have 2 differents widgets for the page to differentiate the language

2024-06-06 08:41 UTC, MaximeAlgosup commented on adopte_a_candidate/lib/pages/profile_page.dart
The profile page is too long and too messi, it should be divided in several widgets to improve the readability

2024-06-06 08:42 UTC, MaximeAlgosup commented on adopte_a_candidate/lib/pages/settings.dart
The setting page is too long and too messi, it should be divided in several widgets to improve the readability

2024-06-06 08:42 UTC, MaximeAlgosup commented on adopte_a_candidate/lib/pages/sign_up.dart
We should not have 2 differents widgets for the page to differentiate the language

2024-06-06 08:45 UTC, MaximeAlgosup requested changes
Many things must be changed before taking this version as a work base. So I refuse the request

2024-06-10 07:35 UTC, Clementine951 approved these changes
Some changes are needed on the SettingsPage branch, but it doesn't bring any crash or issues.

2024-06-10 07:38 UTC, MaximeAlgosup approved these changes
Not everything add been changed, but since it's supposed to be change in the next pull request I accept this one

2024-06-10 07:38 UTC, merged